### ISSUE TITLE
How to render into a parent element?

### ISSUE THREAD

**Issue by tehandyb** [d3plus/d3plus-treemap#36]
Hi I didn't see in the example how to render the treemap into a parent container element. In the d3plus main repo I see you use the container() function, but don't see how to do it here.

**Comment by davelandry** [comment]
With 2.x, we've changed .container( ) to .select( ). I just created an example to show how it's used (spoiler: it's the same as container): http://d3plus.org/examples/d3plus-treemap/selecting-container/

This isn't listed in the main d3plus-treemap docs because it actually gets inherited from a Class in d3plus-viz: https://github.com/d3plus/d3plus-viz#Viz

The docs are a little confusing at the moment, but we'll be (hopefully) solving that before the launch of 2.0.
